# Generated by Django 4.0.3 on 2022-03-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priortiy',
            new_name='priority',
        ),
    ]
