# Generated by Django 4.0.3 on 2022-03-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_App', '0002_rename_priortiy_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2022-03-12'),
            preserve_default=False,
        ),
    ]
